import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import localFont from "next/font/local";
import MainHeader from "@/components/MainHeader";
import { getUser } from "@/lib/firebase/getUser";
import Providers from "../providers";

export const inter = Inter({ subsets: ["latin"] });

const jetBrainsMono = localFont({
  src: "../../../public/fonts/JetBrainsMono-Medium.woff2",
  display: "swap",
  variable: "--font-jetBrainsMono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  movies,
  reviews,
}: Readonly<{
  children: React.ReactNode;
  movies: React.ReactNode;
  reviews: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="ko" className={inter.className}>
      <body className={`${jetBrainsMono.variable} antialiased`}>
        <Providers initialUser={user}>
          <MainHeader />
          <div>{children}</div>
          <div>{movies}</div>
          <div>{reviews}</div>
        </Providers>
      </body>
    </html>
  );
}
