import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import localFont from "next/font/local";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

const jetBrainsMono = localFont({
  src: "../../public/fonts/JetBrainsMono-Medium.woff2",
  display: "swap",
  preload: true,
  variable: "--font-jetBrainsMono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={inter.className}>
      <body className={`${jetBrainsMono.variable} antialiased`}>
        <Providers>
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
